name: graph_convnets
channels:
- pytorch 
dependencies:
#- cuda90 # if cuda 9.0
- pytorch=0.3.1
- torchvision=0.2.0
- numpy=1.14.2
- mkl=2018.0.2
- ipython=6.3.1
- jupyter=1.0.0
- scipy=1.0.1
- matplotlib=2.2.2
- networkx=2.1
- scikit-learn=0.19.1

